### ISSUE TITLE
Hangs at 16k+ requests

### ISSUE THREAD

**Issue by wess** [elliottminns/blackfish#19]
running `ab -r -n 10000 -c 100 http://localhost:8080/` once is fine, but only 4.2k average RPS, but if you run it a second time, it hangs at 6k requests and never crashes or dies. I suspect that it's not letting go of clients fast enough.

**Comment by elliottminns** [comment]
Which OS was this in, Linux or OS X?

**Comment by elliottminns** [comment]
I've managed to replicate this so will begin investigating :+1:

**Comment by elliottminns** [comment]
So, I've been testing this with other web frameworks, including Express. They all hang after 16000 requests in short succession. 

It appears that this is an operating system behaviour in regards to sockets rather than an issue with the web server. I'm going to test it out on a hosted platform to see if it affects the behaviour differently before closing this issue however. 

Interestingly, with express, using `ab -r -n 10000 -c 100 http://localhost:3000/` I get:

 `Requests per second:    1804.12 [#/sec] (mean)`.

With Blackfish, my results are around: 

`Requests per second:    4266.94 [#/sec] (mean)`

Both of these were using a release version on my local machine.

**Comment by Keloran** [comment]
can this be solved by having a pid/sock/fcgi hook, so that something like NGINX which can handle alot more connections, can handle the balance for it

e.g. if you know that blackfish/swift can only handle 16k, then you can set nginx to load-balance and trigger / access 1+n instances of blackfish

**Comment by elliottminns** [comment]
I need to test this properly with NGINX to see what issue it runs in to, but I'm sure there will be a proper solution for it.

Seeming as though Node.js servers running on my local machine can also only handle 16k requests, I'm assuming that this is an issue that has already been solved.

**Comment by wess** [comment]
Thanks for looking into it. I also did some research on this. Wondering if there is something with OS X limiting the number. Also there is a PCRE bug in AB that could potentially cause the RPS numbers to be off as well.
